DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS utilities;
DROP TABLE IF EXISTS appliances;
DROP TABLE IF EXISTS kitchen;
DROP TABLE IF EXISTS furniture;
DROP TABLE IF EXISTS supplies;

CREATE TABLE tenants (
    FIRST_NAME VARCHAR(250) PRIMARY KEY,
    LAST_NAME VARCHAR(250),
    PHONE VARCHAR(250),
    EMAIL VARCHAR(250)
);

INSERT INTO tenants (FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES
    ('Julius', 'Co', '9095516033', 'junna2185@gmail.com'),
    ('Pei-Wen', 'Yang', '9288211136', 'peiwwen.yang@gmail.com'),
    ('Yushi', 'Li', NULL, NULL),
    ('Harry', 'You', NULL, NULL);

CREATE TABLE utilities (
    ITEM VARCHAR(250) PRIMARY KEY,
    PRICE INT,
    ASSIGNED VARCHAR(250) FOREIGN KEY REFERENCES tenants(FIRST_NAME)
    LINK VARCHAR(250)
);

CREATE TABLE appliances (
    ITEM VARCHAR(250) PRIMARY KEY,
    PRICE INT,
    ASSIGNED VARCHAR(250) FOREIGN KEY REFERENCES tenants(FIRST_NAME)
    LINK VARCHAR(250)
);

CREATE TABLE kitchen (
    ITEM VARCHAR(250) PRIMARY KEY,
    PRICE INT,
    ASSIGNED VARCHAR(250) FOREIGN KEY REFERENCES tenants(FIRST_NAME)
    LINK VARCHAR(250)
);

CREATE TABLE furniture (
    ITEM VARCHAR(250) PRIMARY KEY,
    PRICE INT,
    ASSIGNED VARCHAR(250) FOREIGN KEY REFERENCES tenants(FIRST_NAME)
    LINK VARCHAR(250)
);

CREATE TABLE supplies (
    ITEM VARCHAR(250) PRIMARY KEY,
    PRICE INT,
    ASSIGNED VARCHAR(250) FOREIGN KEY REFERENCES tenants(FIRST_NAME)
    LINK VARCHAR(250)
);

